apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: worker
spec:
  template:
    spec:
      serviceAccountName: worker-sa@${PROJECT}.iam.gserviceaccount.com
      containers:
        - image: gcr.io/cloudrun/placeholder
          env:
            - name: GCP_PROJECT
              value: ${PROJECT}
            - name: GCP_REGION
              value: ${REGION}
      containerConcurrency: 1
      timeoutSeconds: 60
