import { defineConfig } from 'vitest/config';

export default defineConfig({
  test: {
    projects: [
      'packages/*/vitest.config.ts',
    ],
    coverage: {
      watermarks: {
        statements: [80, 95],
        branches: [80, 95],
        functions: [80, 95],
        lines: [80, 95],
      },
      exclude: [
        '**/tests/**',
        '**/types.ts',
        '**/types/*.ts',
        'packages/playwright/src/translations/**',
        // Barrel re-exports — no executable statements of their own
        'packages/ai/src/index.ts',
        'packages/bdd/src/index.ts',
        'packages/bdd/src/steps/index.ts',
        'packages/controller/src/index.ts',
        'packages/controller/src/runner/index.ts',
        'packages/executor/src/index.ts',
        'packages/executor/src/types/index.ts',
        'packages/gherker/src/index.ts',
        'packages/gherkin/src/index.ts',
        'packages/gherkin/src/locator/index.ts',
        // Generated by Peggy from parser.peggy; not hand-maintained source.
        'packages/gherkin/src/locator/parser.js',
        'packages/journal/src/index.ts',
        'packages/journal/src/sink/index.ts',
        'packages/journal/src/sink/no-sink.ts',
        'packages/letsrunit/src/index.ts',
        'packages/mailbox/src/index.ts',
        'packages/mcp-server/src/tools/index.ts',
        'packages/playwright/src/index.ts',
        'packages/playwright/src/selector/index.ts',
        'packages/store/src/index.ts',
        'packages/utils/src/index.ts',
      ],
    },
  },
});
