import { describe, expect, it } from 'vitest';
import { deltaSteps, makeFeature, parseFeature } from '../src/feature';

describe('makeFeature', () => {
  it('renders feature text with description, background, scenario, and comments', () => {
    const feature = makeFeature({
      name: 'Account settings',
      description: 'Update profile\nSave and verify',
      background: ['Given I am logged in'],
      steps: ['When I update my profile', 'Then I see a success message'],
      comments: 'generated by AI\nreviewed by QA',
    });

    expect(feature).toBe(
      [
        'Feature: Account settings',
        '',
        '  Update profile',
        '  Save and verify',
        '',
        '  Background:',
        '    Given I am logged in',
        '',
        '  Scenario:',
        '    When I update my profile',
        '    Then I see a success message',
        '',
        '  # generated by AI',
        '  # reviewed by QA',
        '',
      ].join('\n'),
    );
  });
});

describe('parseFeature', () => {
  it('parses step keywords, comments, doc strings, and tables', () => {
    const parsed = parseFeature(`
Feature: Checkout
  user can submit order

  Scenario: submit
    Given I open the checkout
    And I fill shipping details
    * I accept terms
    Then I paste payload:
      """
      hello
      world
      """
    And I provide details:
      | key | value |
      | a   | b     |

  # keep this
  # and this
    `.trim());

    expect(parsed.name).toBe('Checkout');
    expect(parsed.description?.trim()).toBe('user can submit order');
    expect(parsed.comments).toBe('# keep this\n# and this');
    expect(parsed.steps).toEqual([
      'Given I open the checkout',
      'Given I fill shipping details',
      'Given I accept terms',
      'Then I paste payload:\n"""\nhello\nworld\n"""',
      'Then I provide details:\n| key | value |\n| a | b |',
    ]);
  });

  it('wraps raw step text that does not include Feature/Scenario headers', () => {
    const parsed = parseFeature(`
Given I open the page
And I log in
    `.trim());

    expect(parsed.name).toBe('');
    expect(parsed.steps).toEqual([
      'Given I open the page',
      'Given I log in',
    ]);
  });

  it('keeps a provided Scenario header when wrapping bare scenario input', () => {
    const parsed = parseFeature(`
Scenario: login
Given I open the page
When I sign in
Then I see dashboard
    `.trim());

    expect(parsed.name).toBe('');
    expect(parsed.steps).toEqual([
      'Given I open the page',
      'When I sign in',
      'Then I see dashboard',
    ]);
  });

  it('returns undefined comments when no comments exist', () => {
    const parsed = parseFeature(`
Feature: No comments

  Scenario: run
    Given I do something
    `.trim());

    expect(parsed.comments).toBeUndefined();
  });

  it('ignores keyword-only steps with no text content', () => {
    const parsed = parseFeature(`
Feature: Empty text

  Scenario: run
    Given
    Then done
    `.trim());

    expect(parsed.steps).toEqual([
      'Then done',
    ]);
  });

  it('returns empty steps when only scenario outlines are present', () => {
    const parsed = parseFeature(`
Feature: Outlines only
  shared description

  Scenario Outline: fill form
    Given I enter <value>

    Examples:
      | value |
      | one   |
    `.trim());

    expect(parsed.name).toBe('');
    expect(parsed.description?.trim()).toBe('shared description');
    expect(parsed.steps).toEqual([]);
  });
});

describe('deltaSteps', () => {
  it('returns only new tail steps after overlap', () => {
    const prev = ['Given A', 'When B', 'Then C'];
    const next = ['When B', 'Then C', 'And D'];

    expect(deltaSteps(prev, next)).toEqual(['And D']);
  });

  it('returns all steps when there is no overlap', () => {
    expect(deltaSteps(['Given A'], ['When B'])).toEqual(['When B']);
  });
});
