steps:
  - name: gcr.io/cloud-builders/gcloud
    args: [
      'run','deploy','worker',
      '--source','apps/worker',
      '--region','${_REGION}',
      '--service-account','worker-sa@${PROJECT_ID}.iam.gserviceaccount.com',
      '--set-env-vars','GCP_PROJECT=${PROJECT_ID},GCP_REGION=${_REGION}'
    ]
substitutions:
  _REGION: europe-west4
