steps:
  - name: gcr.io/cloud-builders/gcloud
    dir: apps/runner
    args: ['builds','submit','--tag','${_IMG}']
  - name: gcr.io/cloud-builders/gcloud
    args: [
      'run','jobs','deploy','runner',
      '--image','${_IMG}',
      '--region','${_REGION}',
      '--tasks','1','--max-retries','0','--task-timeout','600s',
      '--service-account','runner-sa@${PROJECT_ID}.iam.gserviceaccount.com',
      '--set-env-vars','GCP_PROJECT=${PROJECT_ID},GCP_REGION=${_REGION},ARTIFACT_BUCKET=${_BUCKET}'
    ]
substitutions:
  _REGION: europe-west4
  _BUCKET: runs-artifacts-${PROJECT_ID}
  _IMG: ${_REGION}-docker.pkg.dev/${PROJECT_ID}/runner/runner:latest
