name: Unit Tests
on:
  pull_request:
    branches: [ main ]

jobs:
  packages:
    name: Unit Tests ${{ matrix.project }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        project:
          - "@letsrunit/playwright"
          - "@letsrunit/bdd"
          - "@letsrunit/executor"
          - "@letsrunit/gherker"
          - "@letsrunit/controller"
          - "@letsrunit/gherkin"
          - "@letsrunit/mailbox"
          - "@letsrunit/journal"
          - "@letsrunit/utils"
          - "@letsrunit/ai"
          - "@letsrunit/mcp-server"
    steps:
      - uses: actions/checkout@v6
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn build:packages

      - name: Run Tests
        run: yarn test --project ${{ matrix.project }}

  compat:
    name: Compat Test ${{ matrix.workspace }}
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/playwright:v1.59.1-noble
    strategy:
      fail-fast: false
      matrix:
        workspace:
          - "@letsrunit/compat-react"
          - "@letsrunit/compat-angular"
    steps:
      - uses: actions/checkout@v6
      - name: Enable Corepack
        run: corepack enable
      - uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: "yarn"

      - name: Install dependencies
        run: yarn install --immutable

      - name: Build packages
        run: yarn build:packages

      - name: Install Playwright Browsers
        run: yarn workspace ${{ matrix.workspace }} playwright install chromium

      - name: Run Tests
        run: yarn workspace ${{ matrix.workspace }} test
